name: Test Site
favicon: null
layout_spectrum: 0.7897722979541868
typography_spectrum: 0.6919553084298968
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9010203033685684
  lightness: 0.5130851399153471
  saturation: 0.02226504497230053
  rhythmicContrast: 0.5353670904878527
purpose: []
